version: 2.1

orbs:
    node: circleci/node@7.1.0

jobs:
    schedule-run:
        executor: node/default
        steps:
            - checkout

            - run:
                  name: Enable corepack & pnpm 10.x
                  command: |
                      corepack enable
                      corepack prepare pnpm@10.13.0 --activate
                      pnpm --version

            - restore_cache:
                  keys:
                      - v1-pnpm-store-{{ checksum "pnpm-lock.yaml" }}
                      - v1-pnpm-store-

            - run:
                  name: Install dependencies
                  command: pnpm install --frozen-lockfile

            - save_cache:
                  key: v1-pnpm-store-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - ~/.pnpm-store
                      - node_modules

            - run:
                  name: Run schedule
                  command: node --run start
                  environment:
                      DISCORD_WEBHOOK: $URL

workflows:
    schedule:
        triggers:
            - schedule:
                  cron: "0 0 * * *"
                  filters:
                      branches:
                          only: main
        jobs:
            - schedule-run
